services:
  # Go server
  go-server:
    container_name: go_server
    build: go/.
    #depends_on:
    #  - grpc
    ports:
      - 80:80
      - 443:443
      - 9876:5432 # 9876 is a random port I picked. Can be anything
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      DOMAIN_NAME: ${DOMAIN}
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
      - frontend-build:/app/frontendreact/build
    restart: always
    networks:
      - pg_network

  # gRPC server
  #grpc:
  #  container_name: python_grpc_server
  #  build: python/grpc-server/.
  #  ports:
  #    - 50051:50051
  #  restart: always
  #  networks:
  #    - pg_network

  # React frontend
  react-app:
    container_name: react_app
    build: frontendreact/.
    ports:
      - 3000:3000
    depends_on:
      - go-server
    environment:
      - NODE_ENV=production
    volumes:
      - frontend-build:/app/frontendreact/build
    networks:
      - pg_network

volumes:
  frontend-build:

networks:
  pg_network:
    external: true
