services:
  # Go server
  go-server:
    container_name: go_server
    build: go/.
    depends_on:
      - grpc
      - postgres
    ports:
      - 80:80
      - 443:443
      - 9876:5432 # 9876 is a random port I picked. Can be anything
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      DOMAIN_NAME: ${DOMAIN}
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
    restart: always

  # gRPC server
  grpc:
    container_name: python_grpc_server
    build: python/grpc-server/.
    ports:
      - 50051:50051
    restart: always

  # Postgres database using PostGIS 
  postgres:
    image: postgis/postgis
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ~/PG_DATA:/var/lib/postgresql/data
    restart: always

  # React frontend
  react-app:
    container_name: react_app
    build:
      context: .
      dockerfile: frontendreact/.
    ports:
      - 3000:3000
    depends_on:
      - go-server
    environment:
      - NODE_ENV=production
