// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: busyness.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request format for Python gRPC server
type BusynessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locationid int64 `protobuf:"varint,1,opt,name=locationid,proto3" json:"locationid,omitempty"`
}

func (x *BusynessRequest) Reset() {
	*x = BusynessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_busyness_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusynessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusynessRequest) ProtoMessage() {}

func (x *BusynessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_busyness_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusynessRequest.ProtoReflect.Descriptor instead.
func (*BusynessRequest) Descriptor() ([]byte, []int) {
	return file_busyness_proto_rawDescGZIP(), []int{0}
}

func (x *BusynessRequest) GetLocationid() int64 {
	if x != nil {
		return x.Locationid
	}
	return 0
}

// Reply format from to Go stub/client
type BusynessReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Busyness float32 `protobuf:"fixed32,1,opt,name=busyness,proto3" json:"busyness,omitempty"`
}

func (x *BusynessReply) Reset() {
	*x = BusynessReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_busyness_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusynessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusynessReply) ProtoMessage() {}

func (x *BusynessReply) ProtoReflect() protoreflect.Message {
	mi := &file_busyness_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusynessReply.ProtoReflect.Descriptor instead.
func (*BusynessReply) Descriptor() ([]byte, []int) {
	return file_busyness_proto_rawDescGZIP(), []int{1}
}

func (x *BusynessReply) GetBusyness() float32 {
	if x != nil {
		return x.Busyness
	}
	return 0
}

var File_busyness_proto protoreflect.FileDescriptor

var file_busyness_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x31, 0x0a, 0x0f, 0x42, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x0d, 0x42, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73,
	0x32, 0x40, 0x0a, 0x08, 0x42, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x34, 0x0a, 0x0e,
	0x53, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x10,
	0x2e, 0x42, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0e, 0x2e, 0x42, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_busyness_proto_rawDescOnce sync.Once
	file_busyness_proto_rawDescData = file_busyness_proto_rawDesc
)

func file_busyness_proto_rawDescGZIP() []byte {
	file_busyness_proto_rawDescOnce.Do(func() {
		file_busyness_proto_rawDescData = protoimpl.X.CompressGZIP(file_busyness_proto_rawDescData)
	})
	return file_busyness_proto_rawDescData
}

var file_busyness_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_busyness_proto_goTypes = []any{
	(*BusynessRequest)(nil), // 0: BusynessRequest
	(*BusynessReply)(nil),   // 1: BusynessReply
}
var file_busyness_proto_depIdxs = []int32{
	0, // 0: Busyness.SendLocationID:input_type -> BusynessRequest
	1, // 1: Busyness.SendLocationID:output_type -> BusynessReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_busyness_proto_init() }
func file_busyness_proto_init() {
	if File_busyness_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_busyness_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BusynessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_busyness_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BusynessReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_busyness_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_busyness_proto_goTypes,
		DependencyIndexes: file_busyness_proto_depIdxs,
		MessageInfos:      file_busyness_proto_msgTypes,
	}.Build()
	File_busyness_proto = out.File
	file_busyness_proto_rawDesc = nil
	file_busyness_proto_goTypes = nil
	file_busyness_proto_depIdxs = nil
}
