// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: recommendations.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request format for Python gRPC server
type RecommendationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datetime string `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"` //Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *RecommendationRequest) Reset() {
	*x = RecommendationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRequest) ProtoMessage() {}

func (x *RecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRequest.ProtoReflect.Descriptor instead.
func (*RecommendationRequest) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendationRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *RecommendationRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Reply format from to Go stub/client
type RecommendationReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Lat  float32 `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng  float32 `protobuf:"fixed32,4,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *RecommendationReply) Reset() {
	*x = RecommendationReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationReply) ProtoMessage() {}

func (x *RecommendationReply) ProtoReflect() protoreflect.Message {
	mi := &file_recommendations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationReply.ProtoReflect.Descriptor instead.
func (*RecommendationReply) Descriptor() ([]byte, []int) {
	return file_recommendations_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendationReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecommendationReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecommendationReply) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RecommendationReply) GetLng() float32 {
	if x != nil {
		return x.Lng
	}
	return 0
}

var File_recommendations_proto protoreflect.FileDescriptor

var file_recommendations_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x5d, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x32, 0x56, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x44, 0x0a, 0x12, 0x53, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recommendations_proto_rawDescOnce sync.Once
	file_recommendations_proto_rawDescData = file_recommendations_proto_rawDesc
)

func file_recommendations_proto_rawDescGZIP() []byte {
	file_recommendations_proto_rawDescOnce.Do(func() {
		file_recommendations_proto_rawDescData = protoimpl.X.CompressGZIP(file_recommendations_proto_rawDescData)
	})
	return file_recommendations_proto_rawDescData
}

var file_recommendations_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recommendations_proto_goTypes = []any{
	(*RecommendationRequest)(nil), // 0: RecommendationRequest
	(*RecommendationReply)(nil),   // 1: RecommendationReply
}
var file_recommendations_proto_depIdxs = []int32{
	0, // 0: Recommendation.SendRecommendation:input_type -> RecommendationRequest
	1, // 1: Recommendation.SendRecommendation:output_type -> RecommendationReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recommendations_proto_init() }
func file_recommendations_proto_init() {
	if File_recommendations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recommendations_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RecommendationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendations_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RecommendationReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recommendations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendations_proto_goTypes,
		DependencyIndexes: file_recommendations_proto_depIdxs,
		MessageInfos:      file_recommendations_proto_msgTypes,
	}.Build()
	File_recommendations_proto = out.File
	file_recommendations_proto_rawDesc = nil
	file_recommendations_proto_goTypes = nil
	file_recommendations_proto_depIdxs = nil
}
