# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: busyness.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62usyness.proto\"%\n\x0f\x42usynessRequest\x12\x12\n\nlocationid\x18\x01 \x01(\x03\"!\n\rBusynessReply\x12\x10\n\x08\x62usyness\x18\x01 \x01(\t2@\n\x08\x42usyness\x12\x34\n\x0eSendLocationID\x12\x10.BusynessRequest\x1a\x0e.BusynessReply\"\x00\x42\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'busyness_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_BUSYNESSREQUEST']._serialized_start=18
  _globals['_BUSYNESSREQUEST']._serialized_end=55
  _globals['_BUSYNESSREPLY']._serialized_start=57
  _globals['_BUSYNESSREPLY']._serialized_end=90
  _globals['_BUSYNESS']._serialized_start=92
  _globals['_BUSYNESS']._serialized_end=156
# @@protoc_insertion_point(module_scope)
