# Import Python image from Docker Hub
FROM python

# Set working directory in container
WORKDIR /app

# Copy requirements.txt into container
COPY requirements.txt .

# Install dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy remaining files to server
COPY *.py .

# Expose gRPC server port
EXPOSE 50051

# Set command to run server
CMD ["python3", "-u", "recommendations_server.py"]
