# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\"+\n\x15RecommendationRequest\x12\x12\n\nlocationid\x18\x01 \x01(\x03\"\'\n\x13RecommendationReply\x12\x10\n\x08\x62usyness\x18\x01 \x01(\t2V\n\x0eRecommendation\x12\x44\n\x12SendRecommendation\x12\x16.RecommendationRequest\x1a\x14.RecommendationReply\"\x00\x42\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=25
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=68
  _globals['_RECOMMENDATIONREPLY']._serialized_start=70
  _globals['_RECOMMENDATIONREPLY']._serialized_end=109
  _globals['_RECOMMENDATION']._serialized_start=111
  _globals['_RECOMMENDATION']._serialized_end=197
# @@protoc_insertion_point(module_scope)
