# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: busyness.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62usyness.proto\x12\x08\x62usyness\"&\n\x0f\x42usynessRequest\x12\x13\n\x0blocation_id\x18\x01 \x01(\x05\"$\n\x10\x42usynessResponse\x12\x10\n\x08\x62usyness\x18\x01 \x01(\t2]\n\x11\x42usynessPredictor\x12H\n\x0fPredictBusyness\x12\x19.busyness.BusynessRequest\x1a\x1a.busyness.BusynessResponseB\x13Z\x11../go/go/busynessb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'busyness_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021../go/go/busyness'
  _globals['_BUSYNESSREQUEST']._serialized_start=28
  _globals['_BUSYNESSREQUEST']._serialized_end=66
  _globals['_BUSYNESSRESPONSE']._serialized_start=68
  _globals['_BUSYNESSRESPONSE']._serialized_end=104
  _globals['_BUSYNESSPREDICTOR']._serialized_start=106
  _globals['_BUSYNESSPREDICTOR']._serialized_end=199
# @@protoc_insertion_point(module_scope)
