// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: busyness.proto

package busyness

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	BusynessPredictor_PredictBusyness_FullMethodName = "/busyness.BusynessPredictor/PredictBusyness"
)

// BusynessPredictorClient is the client API for BusynessPredictor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BusynessPredictorClient interface {
	PredictBusyness(ctx context.Context, in *BusynessRequest, opts ...grpc.CallOption) (*BusynessResponse, error)
}

type busynessPredictorClient struct {
	cc grpc.ClientConnInterface
}

func NewBusynessPredictorClient(cc grpc.ClientConnInterface) BusynessPredictorClient {
	return &busynessPredictorClient{cc}
}

func (c *busynessPredictorClient) PredictBusyness(ctx context.Context, in *BusynessRequest, opts ...grpc.CallOption) (*BusynessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BusynessResponse)
	err := c.cc.Invoke(ctx, BusynessPredictor_PredictBusyness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusynessPredictorServer is the server API for BusynessPredictor service.
// All implementations must embed UnimplementedBusynessPredictorServer
// for forward compatibility
type BusynessPredictorServer interface {
	PredictBusyness(context.Context, *BusynessRequest) (*BusynessResponse, error)
	mustEmbedUnimplementedBusynessPredictorServer()
}

// UnimplementedBusynessPredictorServer must be embedded to have forward compatible implementations.
type UnimplementedBusynessPredictorServer struct {
}

func (UnimplementedBusynessPredictorServer) PredictBusyness(context.Context, *BusynessRequest) (*BusynessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictBusyness not implemented")
}
func (UnimplementedBusynessPredictorServer) mustEmbedUnimplementedBusynessPredictorServer() {}

// UnsafeBusynessPredictorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusynessPredictorServer will
// result in compilation errors.
type UnsafeBusynessPredictorServer interface {
	mustEmbedUnimplementedBusynessPredictorServer()
}

func RegisterBusynessPredictorServer(s grpc.ServiceRegistrar, srv BusynessPredictorServer) {
	s.RegisterService(&BusynessPredictor_ServiceDesc, srv)
}

func _BusynessPredictor_PredictBusyness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusynessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusynessPredictorServer).PredictBusyness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusynessPredictor_PredictBusyness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusynessPredictorServer).PredictBusyness(ctx, req.(*BusynessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BusynessPredictor_ServiceDesc is the grpc.ServiceDesc for BusynessPredictor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusynessPredictor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "busyness.BusynessPredictor",
	HandlerType: (*BusynessPredictorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PredictBusyness",
			Handler:    _BusynessPredictor_PredictBusyness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "busyness.proto",
}
