// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: busyness.proto

package busyness

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusynessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId int32 `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
}

func (x *BusynessRequest) Reset() {
	*x = BusynessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_busyness_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusynessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusynessRequest) ProtoMessage() {}

func (x *BusynessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_busyness_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusynessRequest.ProtoReflect.Descriptor instead.
func (*BusynessRequest) Descriptor() ([]byte, []int) {
	return file_busyness_proto_rawDescGZIP(), []int{0}
}

func (x *BusynessRequest) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

type BusynessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Busyness string `protobuf:"bytes,1,opt,name=busyness,proto3" json:"busyness,omitempty"`
}

func (x *BusynessResponse) Reset() {
	*x = BusynessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_busyness_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusynessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusynessResponse) ProtoMessage() {}

func (x *BusynessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_busyness_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusynessResponse.ProtoReflect.Descriptor instead.
func (*BusynessResponse) Descriptor() ([]byte, []int) {
	return file_busyness_proto_rawDescGZIP(), []int{1}
}

func (x *BusynessResponse) GetBusyness() string {
	if x != nil {
		return x.Busyness
	}
	return ""
}

var File_busyness_proto protoreflect.FileDescriptor

var file_busyness_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x32, 0x0a, 0x0f, 0x42, 0x75,
	0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x2e,
	0x0a, 0x10, 0x42, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x32, 0x5d,
	0x0a, 0x11, 0x42, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x48, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x42, 0x75,
	0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x19, 0x2e, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73,
	0x73, 0x2e, 0x42, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x42, 0x75, 0x73,
	0x79, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a,
	0x11, 0x2e, 0x2e, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x62, 0x75, 0x73, 0x79, 0x6e, 0x65,
	0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_busyness_proto_rawDescOnce sync.Once
	file_busyness_proto_rawDescData = file_busyness_proto_rawDesc
)

func file_busyness_proto_rawDescGZIP() []byte {
	file_busyness_proto_rawDescOnce.Do(func() {
		file_busyness_proto_rawDescData = protoimpl.X.CompressGZIP(file_busyness_proto_rawDescData)
	})
	return file_busyness_proto_rawDescData
}

var file_busyness_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_busyness_proto_goTypes = []any{
	(*BusynessRequest)(nil),  // 0: busyness.BusynessRequest
	(*BusynessResponse)(nil), // 1: busyness.BusynessResponse
}
var file_busyness_proto_depIdxs = []int32{
	0, // 0: busyness.BusynessPredictor.PredictBusyness:input_type -> busyness.BusynessRequest
	1, // 1: busyness.BusynessPredictor.PredictBusyness:output_type -> busyness.BusynessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_busyness_proto_init() }
func file_busyness_proto_init() {
	if File_busyness_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_busyness_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BusynessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_busyness_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BusynessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_busyness_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_busyness_proto_goTypes,
		DependencyIndexes: file_busyness_proto_depIdxs,
		MessageInfos:      file_busyness_proto_msgTypes,
	}.Build()
	File_busyness_proto = out.File
	file_busyness_proto_rawDesc = nil
	file_busyness_proto_goTypes = nil
	file_busyness_proto_depIdxs = nil
}
