# Use Go image from Docker Hub
FROM golang:1.22

# Set working directory in container
WORKDIR /app

# Copy Files to container
COPY . .

# Update go.mod and go.sum
RUN go mod tidy

# Download dependencies and verify integrity of files
RUN go mod download && go mod verify

# Build go app
RUN go build -o bin .

# Set the entrypoint into the go app
ENTRYPOINT ["/app/bin"]
