# Use an official Node.js runtime as the base image
FROM node:18-alpine as build

# Set the working directory in the container
WORKDIR /app


# Continue with your Dockerfile steps
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the app source code to the working directory
COPY . .

# Build the React app
RUN npm run build

# Expose the port that the app will run on
EXPOSE 3000

# Production stage (to copy static files)
FROM node:18-alpine as production

# Set working directory
WORKDIR /app

# Copy build files from the build stage
COPY --from=build /app/build /app/frontendreact/build

# Ensure the build files are accessible to other containers or the host
VOLUME /app/frontendreact/build

# Define command to run the container
CMD ["tail", "-f", "/dev/null"]
