name: Deploy to Server 

# deploys on every push to main 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 #checks out full repo

# this installs sshpass to allow passing the password non-interactively 
    - name: Install SSH client 
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: SSH and deploy
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_IP_ADDRESS: ${{ secrets.SSH_IP_ADDRESS }}
        
      run: |
        # Use sshpass to SSH into the server, checkout & pull main, restart docker containers with new updated code
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} "
          echo 'Starting deployment' &&
          cd project/SummerProject &&
          git checkout main &&
          git pull origin main &&
          docker-compose down &&
          docker-compose up --build -d
          "
