# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches:
      - DEV 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Go test cache
        run: go clean -testcache
      - uses: actions/checkout@v4
        with:
          ref: DEV
          fetch-depth: 0 

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'


      - name: Change directory to Go project
        run: |
          cd go
          ls
          go mod tidy
            
      - name: Verify TestPrintRecommendation is removed
        run: |
          cd go
          if git grep -q 'TestPrintRecommendation'; then
            echo "TestPrintRecommendation still exists in the codebase"
            exit 1
          else
            echo "TestPrintRecommendation is not found"
          fi
          
      - name: Build
        run: |
          cd go
          go build -v
  
      - name: Test
        run: |
          cd go
          git grep TestPrintRecommendation
          go test -v .
